### ISSUE TITLE
使用nacos配置限流规则，类型为gw-flow，规则生效但控制台无法查看

### ISSUE THREAD

**Issue by BREAKERSS** [alibaba/Sentinel#1262]
## Issue Description
Use Nacos to configure current rules. The rules take effect, but the dashboard cannot view them

### Describe what happened (or what feature you want)

使用sentinel 集成spring cloud gateway同时用nacos作为配置中心，限流规则从nacos拉去
在配置文件中设置限流的类型为gw-flow，规则生效但是在dashboard无法查看
设置限流类型为degrade，规则生效且在dashboard可以查看

配置文件如下：

```yaml
spring:
    sentinel:
      datasource:
        flow:
          nacos:
            server-addr: localhost:8848 
            dataId: ${spring.application.name}-gw-flow-rules.json #dataId
            groupId: DEFAULT_GROUP 
            rule-type: gw-flow
        degrade:
          nacos:
            server-addr: localhost:8848
            dataId: ${spring.application.name}-degrade-rules.json
            groupId: DEFAULT_GROUP
            rule-type: degrade
```

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3. 

### Tell us your environment

dashboard 版本为1.7.1
sentinel 版本为1.7.1
spring cloud版本为 Greenwich
sentinel-datasource-nacos版本为 1.7.1
