### ISSUE TITLE
[Feature] How can i use Sentinel for springCloud gateway circuitbreaker

### ISSUE THREAD

**Issue by liangyuanpeng** [alibaba/Sentinel#1317]
## Issue Description

Type: *feature*

### Describe what happened (or what feature you want)

I hope I can simply use Sentinel in SpringCloud for circuitbreaker,some like : 

```
        - name: Hystrix
          args:
            name: fallbackcmd
            fallbackUri: forward:/fallback
```  

I searched for a long time for the documentation and didn't find what I wanted.  

I am so sad for it  

What about ``spring-cloud-circuitbreaker-sentinel``  ?

I can not find anything for doc

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3. 

### Anything else we need to know?
Sentinel for SpringCloud Gateway
