### ISSUE TITLE
使用Sentinel从Nacos拉取规则能否同时配置多种数据源

### ISSUE THREAD

**Issue by GongZhengMe** [alibaba/Sentinel#1330]
My request or it is an issue:
I hope I can use the application.yml to config the double rule type: gw-flow &degrade.
Now the gw-flow  work well. But I can't add degrade rule by yml.
```
  sentinel:
      transport:
        dashboard: localhost:8080 
        port: 8720 
      datasource:
        ds:
          nacos:
            server-addr: localhost:8848
            dataId: sentinel-rule-nacos
            groupId: DEFAULT_GROUP
            rule-type: gw-flow
            namespace: 2c4f27b5-f868-40e8-8d6f-429da8d1c6c1
      eager: true  
```
Nacos can push the gw-flow rules to sentinel dashboard
```
[
    {
        "resource": "user-service",
        "grade": 1,
        "count": 5,
        "intervalSec":60,
        "controlBehavior": 0
    }
    ,
     {
        "resource": "file-service",
        "grade": 1,
        "count": 5,
        "intervalSec":60,
        "controlBehavior": 0
    }
]
```
above json is my configuration in  my own Nacos.I think it's really convenient.
can I config degrade rule by this way  and they simultaneously exist?

**Comment by sczyh30** [comment]
You may create the Nacos data-source manually with your own `Parser`, where you could parse the different kinds of rules from the same original data. Refer: https://github.com/alibaba/Sentinel/wiki/Dynamic-Rule-Configuration

**Comment by GongZhengMe** [comment]
Thanks for reply. Can I ask an another quesion? In future , could you or your team  will add the multi kinds of rules push to the same registry center and sentinel dashboard can get them  by yaml or properties . I think it is a very convenient way for operation and maintenance the sentinel rule .Really hope you can add it.
In the end ,thanks for you and your team invent sentinel.It's awesome!~

**Comment by sczyh30** [comment]
Actually if you're meaning configuring different kinds of data-sources in yaml file, it has been supported in Spring Cloud Alibaba: https://github.com/alibaba/spring-cloud-alibaba/wiki/Sentinel#动态数据源支持

**Comment by GongZhengMe** [comment]
```
datasource:
        flow:
          nacos:
            server-addr: localhost:8848
            dataId: ${spring.application.name}-flow-rules
            groupId: DEFAULT_GROUP
            rule-type: gw-flow
            namespace: 68596b7a-4b17-4a77-8831-2213568ec628
        degrade:
          nacos:
            server-addr: localhost:8848
            dataId: ${spring.application.name}-degrade-rules
            groupId: DEFAULT_GROUP
            rule-type: degrade
            namespace: 68596b7a-4b17-4a77-8831-2213568ec628
        system:
          nacos:
            server-addr: localhost:8848
            dataId: ${spring.application.name}-system-rules
            groupId: DEFAULT_GROUP
            rule-type: system
            namespace: 68596b7a-4b17-4a77-8831-2213568ec628
```
Thanks，I can resolve the problem  like above yaml config.Kind of rule-type by one data-source in yaml.
