### ISSUE TITLE
sentinel默认url-parttern为/*在2.2.0.RELEASE不生效

### ISSUE THREAD

**Issue by tanaduus** [alibaba/Sentinel#1380]
因为从filter改成了interceptor，所以默认的`/*`不能被识别，需要改成`/**`

**Comment by cdfive** [comment]
是的，暂时需要手动配置`/**`：
```
spring:
  cloud:
    sentinel:
      filter:
        url-patterns: /**
```
该配置已在`spring-cloud-alibaba-sentinel`最新2.2.1.RELEASE版本修正。

关联issue：#1279、#1343
