### ISSUE TITLE
spring cloud gateway在nacos 配置启动参数无法在 dashboard中看到

### ISSUE THREAD

**Issue by songjiang951130** [alibaba/Sentinel#1384]
## Issue Description

Type:  *feature request*

### Describe what happened (or what feature you want)

在nacos 中配置如下 spring.yml 文件中关键配置如下
```
project:
  name: gateway-sentinel-name
# -Dcsp.sentinel.app.type=1  -Dcsp.sentinel.dashboard.server=localhost:8080
csp:
  sentinel:
    app:
      type: 1 #网关应用
    dashboard:
      server: localhost:8080
```
### Describe what you expected to happen
如题，只有配置启动参数

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3. 

### Tell us your environment
sentinel 1.7,1
nacos 2.2.0.RELEASE
spring cloud gateway 2.2.2.RELEASE
