### ISSUE TITLE
Spring Cloud Gateway + Sentinel 1.7.1 (SCA), GatewayFlowRule does not take effect

### ISSUE THREAD

**Issue by archx** [alibaba/Sentinel#1468]
## Issue Description

Spring Cloud Gateway 整合 Sentinel 1.7.1 使用 `spring-cloud-starter-alibaba-sentinel` 时， 限流规则不生效

Type: *bug report*

### Describe what happened (or what feature you want)

使用如下配置时，限流规则不生效

Maven pom.xml

```xml
<dependency>
    <groupId>com.alibaba.cloud</groupId>
    <artifactId>spring-cloud-starter-alibaba-sentinel</artifactId>
</dependency>
<dependency>
    <groupId>com.alibaba.cloud</groupId>
    <artifactId>spring-cloud-alibaba-sentinel-gateway</artifactId>
</dependency>
<dependency>
    <groupId>com.alibaba.csp</groupId>
    <artifactId>sentinel-spring-cloud-gateway-adapter</artifactId>
</dependency>
<dependency>
    <groupId>com.alibaba.csp</groupId>
    <artifactId>sentinel-datasource-nacos</artifactId>
</dependency>
<dependency>
    <groupId>com.alibaba.csp</groupId>
    <artifactId>sentinel-transport-simple-http</artifactId>
</dependency>
```

application.yml

```yaml
spring:
  cloud:
    gateway:
      enabled: true
      discovery:
        locator:
          lower-case-service-id: true
      routes:
        - id: service-consumer
          uri: lb://service-consumer
          predicates:
            - Path=/consumer/**
          filters:
            - StripPrefix=1
    sentinel:
      filter:
        enabled: false
      datasource:
        ds1.nacos:
          server-addr: 127.0.0.1:8848
          dataId: gw-flow-sentinel
          groupId: DEFAULT_GROUP
          ruleType: gw-flow
      transport:
        dashboard: 127.0.0.1:8858
        port: 8719
```

Nacos `gw-flow-sentinel`

```json
[
  {
    "resource": "service-consumer",
    "grade": 1,
    "count": 2,
    "strategy": 0,
    "controlBehavior": 0,
    "clusterMode": false
  }
]
```

### Describe what you expected to happen

期待限流规则生效

### How to reproduce it (as minimally and precisely as possible)

1. 使用 `Sentinel Starter`
```xml
<dependency>
    <groupId>com.alibaba.cloud</groupId>
    <artifactId>spring-cloud-starter-alibaba-sentinel</artifactId>
</dependency>
```

### Tell us your environment

macOs Catalina/ JDK 8

- spring-boot.version 1.2.13.RELEASE
- spring-cloud.version Greenwich.SR4
- spring-cloud-alibaba-dependencies 2.1.2.RELEASE

OR

- spring-boot.version 2.2.7.RELEASE
- spring-cloud.version Hoxton.SR4
- spring-cloud-alibaba-dependencies 2.2.1.RELEASE

### Anything else we need to know?

使用以下方式可以使限流规则生效

1. 移除Maven依赖

```xml
<dependency>
    <groupId>com.alibaba.cloud</groupId>
    <artifactId>spring-cloud-starter-alibaba-sentinel</artifactId>
</dependency>
<dependency>
    <groupId>com.alibaba.cloud</groupId>
    <artifactId>spring-cloud-alibaba-sentinel-gateway</artifactId>
</dependency>
```

2. GatewayConfiguration.java

```java
@Configuration
public class GatewayConfiguration {

    private final List<ViewResolver> viewResolvers;
    private final ServerCodecConfigurer serverCodecConfigurer;

    public GatewayConfiguration(ObjectProvider<List<ViewResolver>> viewResolversProvider,
                                ServerCodecConfigurer serverCodecConfigurer) {
        this.viewResolvers = viewResolversProvider.getIfAvailable(Collections::emptyList);
        this.serverCodecConfigurer = serverCodecConfigurer;
    }

    @Bean
    @Order(Ordered.HIGHEST_PRECEDENCE)
    public SentinelGatewayBlockExceptionHandler sentinelGatewayBlockExceptionHandler() {
        // Register the block exception handler for Spring Cloud Gateway.
        return new SentinelGatewayBlockExceptionHandler(viewResolvers, serverCodecConfigurer);
    }

    @Bean
    @Order(Ordered.HIGHEST_PRECEDENCE)
    public GlobalFilter sentinelGatewayFilter() {
        return new SentinelGatewayFilter();
    }

    // 替换yaml配置
    @Autowired
    public void initGatewayRules() {

        String remoteAddress = "127.0.0.1:8848";
        String groupId = "DEFAULT_GROUP";
        String dataId = "gw-flow-sentinel";
        ReadableDataSource<String, Set<GatewayFlowRule>> dataSource = new NacosDataSource<>(remoteAddress, groupId, dataId,
                source -> JSON.parseObject(source, new TypeReference<Set<GatewayFlowRule>>() {
                }));
        GatewayRuleManager.register2Property(dataSource.getProperty());
    }
}
```

3. 使用`JVM`参数连接`Sentinel Dashboard`, 

```text
-Dcsp.sentinel.dashboard.server=127.0.0.1:8858
-Dcsp.sentinel.app.type=1
-Dproject.name=gateway
```
