### ISSUE TITLE
Sentinel dashboard cannot display properly when the spring boot application has a context path

### ISSUE THREAD

**Issue by seedscoder** [alibaba/Sentinel#1474]
## Issue Description

Type: *bug report* or *feature request*

### Describe what you expected to happen

- **Sentinel dashboard cannot display properly when the spring boot application has a context path**

### How to reproduce it (as minimally and precisely as possible)

- application.yml
```yml
server:
  port: 9000
  servlet:
    context-path: /sentinel-demo

spring:
  application:
    name: sentinel-demo
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8080
```

- result
![context path](https://user-images.githubusercontent.com/34568397/81496631-8552fe00-92eb-11ea-9ef5-9aaaeea33f19.png)

- When I delete the context path
![xxx](https://user-images.githubusercontent.com/34568397/81496661-c3502200-92eb-11ea-8198-f094fd9b74cb.png)

### Tell us your environment

- Spring Cloud Alibaba 2.2.0.RELEASE

### Anything else we need to know?

- **What do I need to do to display correctly**

**Comment by cdfive** [comment]
Try add `filter.url-patterns: /**` in application.yml:
```yml
spring:
  application:
    name: sentinel-demo
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8080
      filter:
        url-patterns: /**
```

The `Spring Cloud Alibaba 2.2.1.RELEASE` has improved this configuration by default.

Refer to #1380、#1343
