### ISSUE TITLE
sentinel 使用 nacos 存储，dashboard 新增规则没有保存到nacos

### ISSUE THREAD

**Issue by NineSwordsMonster** [alibaba/Sentinel#1511]
## Issue Description

bug report

### Describe what happened (or what feature you want)
在 dashboard里新增的规则没有存储到nacos

### Describe what you expected to happen

在 dashboard里新增的规则能同步存储到nacos

### How to reproduce it (as minimally and precisely as possible)

1.  启动sentinel dashbaord
2.  配置naocs 
3.  在dashboard 增加配置

### Tell us your environment
jdk8  macos 
```xml
    <properties>
        <java.version>1.8</java.version>
        <spring-cloud-alibaba.version>2.2.1.RELEASE</spring-cloud-alibaba.version>
        <spring-cloud.version>Hoxton.SR3</spring-cloud.version>
    </properties>
```

### Anything else we need to know?

```yaml
spring:
  cloud: 
    sentinel:
      enabled: true
      eager: true
      filter: 
        enabled: false
      transport:
        dashboard: 172.18.1.131:8850
        port: 8851
      datasource:
        ds1:
          nacos:
            server-addr: 172.18.1.131
            namespace: e8a87655-33f5-4c7a-a575-baf37ad30530
            dataId: bka-sentinel-flow
            groupId: bka-sentinel
            rule-type: flow
            flowfile-extension: yaml
        ds2:
          nacos:
            server-addr: 172.18.1.131
            namespace: e8a87655-33f5-4c7a-a575-baf37ad30530
            dataId: bka-sentinel-degrade
            groupId: bka-sentinel
            rule-type: degrade
            flowfile-extension: yaml
        ds3:
          nacos:
            server-addr: 172.18.1.131
            namespace: e8a87655-33f5-4c7a-a575-baf37ad30530
            dataId: bka-sentinel-authority
            groupId: bka-sentinel
            rule-type: authority
            flowfile-extension: yaml
        ds4:
          nacos:
            server-addr: 172.18.1.131
            namespace: e8a87655-33f5-4c7a-a575-baf37ad30530
            dataId: bka-sentinel-system
            groupId: bka-sentinel
            rule-type: system
            flowfile-extension: yaml
        ds5:
          nacos:
            server-addr: 172.18.1.131
            namespace: e8a87655-33f5-4c7a-a575-baf37ad30530
            dataId: bka-sentinel-paramFlow
            groupId: bka-sentinel
            rule-type: param-flow
            flowfile-extension: yaml
```
