### ISSUE TITLE
网关限流目前支持naco动态路由吗？

### ISSUE THREAD

**Issue by lemos1235** [alibaba/Sentinel#1772]
我调试后，启动时会主动发请求获取该 nacos 文件，但是控制台面板没有显示相应的规则。
下面是我的配置：
nacos 配置
```json
 [
   {
     "resource": "uaa_route",
     "controlBehavior": 2,
     "maxQueueingTimeoutMs": 5000,
     "count": 20,
     "grade": 1
   }
 ]
```

spring cloud 相关属性配置
```yaml
    nacos:
      config:
        server-addr: 192.168.0.105:8848
        file-extension: yaml
        shared-configs:
          - application.yaml
          - application-@profiles.active@.yaml
          - application-redis-@profiles.active@.yaml
    sentinel:
      filter:
        enabled: false
      transport:
        dashboard: 192.168.0.105:8080
      datasource:
        ds1:
          nacos:
            server-addr: ${spring.cloud.nacos.config.server-addr}
            group-id: DEFAULT_GROUP
            data-id: ${spring.application.name}-sentinel
            rule-type: flow # ref RuleType
```
