### ISSUE TITLE
Sentinel读取nacos中的限流配置，均匀排队模式下总会先拒绝大量请求，之后进入均匀排队模式

### ISSUE THREAD

**Issue by CNWangTy** [alibaba/Sentinel#1807]
### Describe what happened (or what feature you want)

Sentinel读取nacos中的限流配置，均匀排队模式下总会先拒绝大量请求，之后进入均匀排队模式。
但是直接在控制台中配置均匀排队，则一切正常

### Tell us your environment
gateway中集成了sentinel，数据源配置为nacos配置如下
```
sentinel:
      transport:
        dashboard: localhost:8080
      datasource:
        flow-ds: # flow-ds为自定义数据源ID,保存限流规则
          nacos:
            server-addr: ${spring.cloud.nacos.discovery.server-addr}
            data-id: gw-flow
            group-id: xxxx
            rule-type: flow
            username: nacos
            password: nacos
```
### Anything else we need to know?

![image](https://user-images.githubusercontent.com/41817792/96532269-1c21de80-12be-11eb-9064-a7e3adcd2179.png)

请问是我配置使用的问题还是这样确实会有问题？求指导。
