### ISSUE TITLE
sentinel-dashboard，使用server.servlet.context-path，设置完成，前端页面无法访问

### ISSUE THREAD

**Issue by mrvon2015** [alibaba/Sentinel#1839]
是可以通过自定义server.servlet.context-path 这个配置，使访问路径生效的，但是请求页面没生效，是因为页面不做适配，能否加上这个功能。

**Comment by sczyh30** [comment]
Discussions and contributions are welcomed!

**Comment by xuande** [comment]
我遇到同样的问题。启动sentinel时增加`server.servlet.context-path`导致静态资源加载出错，修改源码后能够正常加载，但是业务应用中通过`spring.cloud.sentinel.transport.dashboard`配置地址若增加contextpath,数据无法上报到dashboard，如下所示：
1. 启动sentine-dashboard
```
java -jar sentinel-dashboard.jar --server.servlet.context-path=/sentinel
```
2. 修改业务应用中的配置
```
spring:
  cloud:
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080/sentinel
```
3. 访问`http://localhost:8080/sentinel`可以正常访问，但是无法显示数据，启动时取消context-path配置后回复正常
