### ISSUE TITLE
gateway sentienl 后流控不生效

### ISSUE THREAD

**Issue by yangzhe09** [alibaba/Sentinel#1860]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)
sentinel 集成网关，使用nacos进行网关流控的持久化，nacos进行动态路由配置，但是在集成后，sentinel的网关流控不生效，可以持久化，但是无法限流

### Describe what you expected to happen
期望sentienl 集成gateway后流控与降级生效

### How to reproduce it (as minimally and precisely as possible)

1. gateway服务 application配置

```yaml
server:
  #设置服务端口
  port: 8090
spring:
  #设置服务名称
  application:
    name: service-gateway
  main:
    allow-bean-definition-overriding: true
  #设置nacos注册地址
  cloud:
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080
    nacos:
      config:
        server-addr: localhost:8848
      discovery:
        server-addr: localhost:8848
    #设置网关配置
    gateway:
      enabled: true
      discovery:
        locator:
          lower-case-service-id: true
      routes:
```

2. sentienl 是单独的服务，未在微服务中集成
3. InMemoryRuleRepositoryAdapter中新增网关流控，

```java
    @Override
    public T save(T entity) {
        if (entity.getId() == null) {
            entity.setId(nextId());
        }
        T processedEntity = preProcess(entity);
        if (processedEntity != null) {
            allRules.put(processedEntity.getId(), processedEntity);
            machineRules.computeIfAbsent(MachineInfo.of(processedEntity.getApp(), processedEntity.getIp(),
                processedEntity.getPort()), e -> new ConcurrentHashMap<>(32))
                .put(processedEntity.getId(), processedEntity);
            appRules.computeIfAbsent(processedEntity.getApp(), v -> new ConcurrentHashMap<>(32))
                .put(processedEntity.getId(), processedEntity);
        }

        return processedEntity;
    }
```

未添加到网关中的规则集合中
