### ISSUE TITLE
sentinel-server配置二级域名访问，其实时监控页面的 metric/queryTopResourceMetric 相关接口没有走二级域名，应该如何配置呢？

### ISSUE THREAD

**Issue by laolunsi** [alibaba/Sentinel#1976]
sentinel 控制台访问配置了二级域名，形如 xxx.com/sentinel，其中【实时监控】页面打开后，metric/queryTopResourceMetric 接口没有走二级域名，请问应该如何解决该问题呢？或者说从哪里入手？谢谢！

![image](https://user-images.githubusercontent.com/14289608/105287847-af86ea80-5bf2-11eb-8870-4db27412895c.png)

我的环境是 Spring-Cloud 应用，应用中关于 sentinel 的配置如下：
```
spring:
  cloud:
    sentinel:
      transport:
        dashboard: 192.168.11.56:8080
```

没有添加其他配置。
