### ISSUE TITLE
Sentinel 控制台加不上规则

### ISSUE THREAD

**Issue by huhudiedie** [alibaba/Sentinel#2185]
## 控制台加不上规则，添加了显示空白，也没有实际效果
![image](https://user-images.githubusercontent.com/67212456/117240152-cfb97d00-ae62-11eb-92ae-ba035a22ad21.png)
![image](https://user-images.githubusercontent.com/67212456/117240161-d516c780-ae62-11eb-9760-a723786d8a44.png)

### 我的客户端是2021.1版本，服务端是1.8.0

这个是配置信息
```yml
spring:
  application:
    name: customer
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        server-addr: localhost:8848
        file-extension: yml
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
```
