### ISSUE TITLE
sentinel dashoboard 只能发现springcloud gateway的服务实例，下游的服务不能实现通信

### ISSUE THREAD

**Issue by litairan1995** [alibaba/Sentinel#2194]
springcloud gateway 相关配置

相关jar包版本
       ```
<dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-gateway</artifactId>
            <version>3.0.2</version>
        </dependency>

        <!-- 注册中心-->
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
            <version>2020.0.RC1</version>
        </dependency>

       <!-- 配置中心 -->
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
            <version>2020.0.RC1</version>
        </dependency>

        <!-- Sentinel流量控制、熔断降级 -->
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-alibaba-sentinel-gateway</artifactId>
            <version>2020.0.RC1</version>
        </dependency>
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-sentinel</artifactId>
            <version>2020.0.RC1</version>
        </dependency>

        <dependency>
            <groupId>com.alibaba.csp</groupId>
            <artifactId>sentinel-datasource-nacos</artifactId>
            <version>1.8.0</version>
        </dependency>
```

配置信息

```
spring:
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8920
      scg:
        fallback:
          response-status: 426
          response-body: "{'code':'426' , 'message':'请求频繁，请稍后重试'}"
      filter:
        enabled: false
      datasource:
        # 名称随意
        flow:
          nacos:
            server-addr: ${spring.cloud.nacos.discovery.server-addr}
            dataId: ${spring.application.name}-gateway-flow
            groupId: DEFAULT_GROUP
            # 规则类型，取值见：
            # com.alibaba.cloud.sentinel.datasource.RuleType
            rule-type: gw-flow
        api:
          nacos:
            server-addr: ${spring.cloud.nacos.discovery.server-addr}
            dataId: ${spring.application.name}-gateway-api
            groupId: DEFAULT_GROUP
            # 规则类型，取值见：
            # com.alibaba.cloud.sentinel.datasource.RuleType
            rule-type: gw-api-group
```

下游服务相关jar包版本
       ```
 <dependency>
            <groupId>com.alibaba.csp</groupId>
            <artifactId>sentinel-datasource-nacos</artifactId>
            <version>1.8.1</version>
        </dependency>

        <!-- https://mvnrepository.com/artifact/com.alibaba.cloud/spring-cloud-starter-alibaba-sentinel -->
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-sentinel</artifactId>
            <version>2020.0.RC1</version>
        </dependency>
```

下游服务配置信息
   
```
spring:
  application:
    name: jurisdiction-center
  cloud:
    nacos:
      discovery:
        server-addr: 120.55.164.146:8848
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
        file-extension: properties
    sentinel:
      transport:
        dashboard: localhost:8920
      enabled: true
      datasource:
        flow:
          nacos:
            server-addr: ${spring.cloud.nacos.discovery.server-addr}
            data-id: ${spring.application.name}-flow-rules
            group-id: SENTINEL_GROUP
            data-type: json
            rule-type: flow
        degrade:
          nacos:
            server-addr: ${spring.cloud.nacos.discovery.server-addr}
            data-id: ${spring.application.name}-degrade-rules
            group-id: DEFAULT_GROUP
            data-type: json
            rule-type: degrade
```
