### ISSUE TITLE
sentinel1.8.1不能读取nacos2.0.2中非public工作空间的配置

### ISSUE THREAD

**Issue by huie2018** [alibaba/Sentinel#2251]
经测试只会读取public下的配置文件，加不加namespace都是访问的public空间
软件版本
```
sentinel1.8.1
nacos2.0.2
```
bootstrap.yml配置
```
spring:
  cloud:
     sentinel:
      eager: true
      transport:
        # sentinel地址
        dashboard: 127.0.0.1:8849
      datasource:
        ds1:
          nacos:
            server-addr: 127.0.0.1:8848
            dataId: qms-sentinel-gateway-dev
            groupId: DEV_GROUP
            namespace: dev
            data-type: json
            rule-type: flow
```
nacos配置截图
![image](https://user-images.githubusercontent.com/40845091/123071945-acb14f80-d447-11eb-923d-53028cc3dffb.png)
