### ISSUE TITLE
spring cloud gateway 整合 sentinel 时 API 名称会有前缀

### ISSUE THREAD

**Issue by Tank-zhu** [alibaba/Sentinel#2293]
版本：
sentinel dashboard  1.8.2
spring cloud gateway Hoxton.SR8

问题：
### ReactiveCompositeDiscoveryClient_  会加个这前缀

![image](https://user-images.githubusercontent.com/10337065/125917032-f858103c-23ca-47c8-b223-15605998b307.png)

**Comment by Tank-zhu** [comment]
找到原因了
org.springframework.cloud.gateway.discovery.DiscoveryClientRouteDefinitionLocator
这个类在构建RouteDefinition时主动加上去的。。。
![image](https://user-images.githubusercontent.com/10337065/125925491-75150b75-7526-4c2e-b69d-8eca9f87bc14.png)

### OK完美解决
![image](https://user-images.githubusercontent.com/10337065/125926019-5dc7c7aa-9cd0-4bfa-ba83-8158eea07832.png)

**Comment by yozhfun** [comment]
原来如此
```yml
spring:
  cloud:
    gateway:
      discovery:
        locator:
          route-id-prefix: your_prefix
```
