### ISSUE TITLE
sentinel dashboard 是否考虑做成类似 `@EnableEurekaServer` 的形式，提供  `@EnableSentinelDashboard`

### ISSUE THREAD

**Issue by zhangyunan1994** [alibaba/Sentinel#2512]
## Issue Description

*feature request*

### Describe what happened (or what feature you want)

sentinel dashboard 是否考虑做成类似 Spring Cloud Eureka Server 的部署方式，比如

```java
@SpringBootApplication
@EnableSentinelDashboard
public class DashboardApplication {
    public static void main(String[] args) {
        SpringApplication.run(DashboardApplication.class, args);
    }
}

```

然后通过一些配置项来确定规则的改动保存在何种存储中（内存、zookeeper、nacos、redis ...） 这样做可以简化二次配置的难度，也能防止用户在二次改造的时候出现问题

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by su787910081** [comment]
dashboard 它就是一个控制台服务器，如果你不用控制台你不启动服务就好了呀。如果你启动了服务，为什么还要关闭它呢？
搞不清楚你的逻辑是什么。

**Comment by zhangyunan1994** [comment]
改成这种方式主要是为了减少改造的出错率，如果只把 dashboard 的数据保存在内存中，是不要进行改造的。如果想把规则保存在其他数据源中，需要自行就行改造，并且文档中提供了一部分改造的例子，如果想把集群流控的功能也生效的话，依然需要修改 dashboard 的源码。这样如果以后既需要维护自己的改造的代码，又要去查看 alibaba/sentinel 是否新增了功能或者解决了 bug, 最后需要维护两份代码。同事自己改造源码也需要进行测试，也存在一部分风险。

**Comment by zhangyunan1994** [comment]
如果改成类似  Spring Cloud Eureka Server 的部署方式，既能统一一下改造的版本，又能提供一些标准化的改造方案，同时作为开源项目，大家也可以一起找改造后的 bug, 这样更容易将项目落地。预期改造效果如下

## 一、提供一个 starter 并能通过注解开启功能

1. 提供 spring-boot-alibaba-sentinel-dashboard-starter
2. 提供 @EnableSentinelDashboard

启动方式如下：

```java
@SpringBootApplication
@EnableSentinelDashboard
public class DashboardApplication {
    public static void main(String[] args) {
        SpringApplication.run(DashboardApplication.class, args);
    }
}
```

## 二、通过配置可以选择不同的存储方式

```yaml
sentinel:
  dashboard:
    cluster: false
    datasource:
      nacos:
        namespace: 3c6f4b6a-511a-42cd-b1dd-35e2523216ac
        server-addr: nacos.cn:80
        group: DEFAULT_GROUP
        username: nacos
        password: nacos

```
