### ISSUE TITLE
sentinel gateway nacos 在1.8.3版本中sentinel无法获取nacos的规则

### ISSUE THREAD

**Issue by tingmag** [alibaba/Sentinel#2549]
### sentinel gateway nacos 在1.8.3版本中sentinel无法获取nacos的规则，
按文档说明加了以下配置：
1、gateway 启动参数添加-Dcsp.sentinel.app.type=1
2、rule-type设置为gw-flow
**结果sentinel始终无法获取规则，并且sentinel-dashboard设置的规则不生效**

### pom.xml
```
<properties>
        <java.version>11</java.version>
</properties>
<dependencyManagement>
    <dependencies>

        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-dependencies</artifactId>
            <version>2020.0.3<</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>

        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-alibaba-dependencies</artifactId>
            <version>2021.1</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>

        <dependency>
            <groupId>com.alibaba.nacos</groupId>
            <artifactId>nacos-client</artifactId>
            <version>2.0.3</version>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-dependencies</artifactId>
            <version>2.5.4</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>

    </dependencies>
</dependencyManagement>
```
### bootstrap.yml
```
spring:
  cloud:
    sentinel:
      filter:
        enabled: false
      eager: true
      transport:
        dashboard: localhost:8718
        client-ip: 192.168.0.205
      datasource:
        ds:
          nacos:
            server-addr: 192.168.0.127:8848
            dataId: sentinel-gateway
            groupId: XX_GROUP
            data-type: json
            rule-type: gw-flow
```
