### ISSUE TITLE
Why is the paramItem configured in NACOS invalid?

### ISSUE THREAD

**Issue by yangxueyong** [alibaba/Sentinel#2555]
I refer to the https://github.com/alibaba/Sentinel/wiki/%E7%BD%91%E5%85%B3%E9%99%90%E6%B5%81

My configuration is as follows:
pom.xml:    [ version : 2.2.8-SNAPSHOT]

```
<dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-sentinel</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-webflux</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-gateway</artifactId>
        </dependency>

        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-alibaba-sentinel-gateway</artifactId>
        </dependency>

        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
        </dependency>

        <dependency>
            <groupId>com.alibaba.csp</groupId>
            <artifactId>sentinel-datasource-nacos</artifactId>
        </dependency>
```

application.yaml 
```
server:
  port: 18085
spring:
  application:
    name: sentinel-spring-cloud-gateway
  cloud:
    nacos:
      username: nacos
      password: nacos
      discovery:
        enabled: true
        register-enabled: false
        server-addr: 127.0.0.1:8848
        ephemeral: false
    gateway:
      enabled: true
      discovery:
        locator:
          lower-case-service-id: true
      routes:
      - id: yxy_route
        uri: lb://service-consumer
        predicates:
        - Path=/ss/**
        filters:
        - StripPrefix=1

    sentinel:
      transport:
        dashboard: localhost:8080
      filter:
        enabled: true
      scg.fallback:
          mode: response
          response-status: 444
          response-body: 1234
      scg:
        order: -100
      datasource.ds.nacos:
        server-addr: 127.0.0.1:8848
        dataId: ${spring.application.name}-sentinel
        groupId: DEFAULT_GROUP
        ruleType: flow


management.endpoints.web.exposure.include: "*"
```

-------------------

When I configured the traffic limiting policy in NACOS as follows:
`[
  {
    "resource": "yxy_route",
    "count": 1,
    "paramItem": {
      "parseStrategy": 3,
      "fieldName": "name",
      "pattern": "123",
      "matchStrategy": 0
    }
  }
]`

When I visit http://127.0.0.1:18085/ss/echo-feign2/2222?name=123, I can indeed be restricted to one access per second, but when I visit http://127.0.0.1:18085/ss/echo-feign2/2222, I am also restricted. Why is this?

I didn't make any other restrictions in the code
