### ISSUE TITLE
Same URL, different HTTP method | URL 相同，http method不同的restful接口怎么分别设置流控

### ISSUE THREAD

**Issue by JiangGuangxing** [alibaba/Sentinel#2641]
在sentinel控制台中，uri相同，http method不同的restful接口在簇点链路中被当做同一个接口统计，请问怎么分别设置流控

**Comment by icodening** [comment]
在配置文件中将以下配置改为true即可
````yaml
spring:
  cloud:
    sentinel:
      http-method-specify: true
````
