### ISSUE TITLE
Sentinel控制台什么都没有显示

### ISSUE THREAD

**Issue by XiFYuW** [alibaba/Sentinel#3087]
**spring-cloud-alibaba版本2022.0.0.0-RC1 集成gateway+Sentinel，配置如下：**
 ```
 sentinel:
      transport:
        port: ${DSENTINEL_PORT:8719}
        dashboard: ${SENRINEL_DASHBOARD:127.0.0.1:8080}
      filter:
        enabled: false
      eager: true
      enabled: true
      datasource:
        ds:
          nacos:
            server-addr: ${NACOS_ADDR:127.0.0.1:8848}
            username: ${NACOS_USERNAME:nacos}
            password: ${NACOS_PASSWORD:nacos}
            namespace: @sentinel.namespace@
            group-id: @profile@
            rule-type: flow
            data-id: meta-admin-app
            data-type: json
```
**正常启动成功，nacos的配置如下：**
![image](https://user-images.githubusercontent.com/33598203/230044222-885ee1af-2e38-49e7-9a17-5c9dcfc0723a.png)

**到这里一切都是正常的，问题是Sentinel控制台什么都没有，如图：**
![image](https://user-images.githubusercontent.com/33598203/230044725-95ac89ba-85da-494b-8668-4289434fb4c4.png)
**pom jar包如下：**
![Uploading image.png…]()
