### ISSUE TITLE
[BUG] Nacos发布流控规则无法到Sentinel Dashboard

### ISSUE THREAD

**Issue by Zengwenliang0416** [alibaba/Sentinel#3442]
## Issue Description

Type: *bug report*

### Describe what happened
# 【Bug】Nacos发布流控规则无法到Sentinel Dashboard

> 版本说明：nacos=2.4.0、Sentinel Dashborad=1.8.8、spring.cloud.alibaba.version=2023.0.1.2

## 依赖

```xml
<!-- sentinel-gateway依赖 -->
<dependency>
    <groupId>com.alibaba.cloud</groupId>
    <artifactId>spring-cloud-alibaba-sentinel-gateway</artifactId>
</dependency>
<!-- sentinel-datasource-nacos依赖 -->
<dependency>
    <groupId>com.alibaba.csp</groupId>
    <artifactId>sentinel-datasource-nacos</artifactId>
</dependency>
```

## 配置

```yaml
spring:
  cloud:
    nacos:
      server-addr:  # Nacos 服务器地址
      username: # Nacos用户名
      password: # Nacos密码
      discovery: # 【配置中心】配置项
        namespace: dev # 命名空间。这里使用 dev 开发环境
        group: DEFAULT_GROUP # 使用的 Nacos 配置分组，默认为 DEFAULT_GROUP
      config: # 【注册中心】配置项
        namespace: dev # 命名空间。这里使用 dev 开发环境
        group: DEFAULT_GROUP # 使用的 Nacos 配置分组，默认为 DEFAULT_GROUP
    sentinel:
      datasource:
        r1:
          nacos:
            username: # Nacos用户名
            password: # Nacos密码
            namespace: dev
            # nacos地址
            server-addr: # Nacos 服务器地址
            # nacos中配置文件的data-id
            data-id: ${spring.application.name}-sentinel
            # nacos 分组
            group-id: DEFAULT_GROUP
            # 规则类型 流控
            rule-type: flow
      transport:
        dashboard: 127.0.0.1:8080
        client-ip: 127.0.0.1
```

## nacos配置流控

由于微服务创建的时候是用的是`dev`命名空间，因此需要在`dev`命名空间中创建配置。

```json
[
	{
        "resource": "system-admin-api",
        "resourceMode": 0,
        "count": 10,
        "grade": 1,
		"controlBehavior": 0,
        "intervalSec": 10,
        "burst": 0,
        "maxQueueingTimeoutMs": 1000
	}
]
```

<img width="1495" alt="image-20240823110214338" src="https://github.com/user-attachments/assets/96114a53-ad2f-4208-970c-c5bf927472e5">
<img width="1511" alt="image-20240823110601723" src="https://github.com/user-attachments/assets/2dd61699-c014-407c-9523-6cda5ed25b89">
此时可以看到我们设置的QPS是10，然后启动Sentinel Dashboard、网关和相应的业务微服务。

访问system-admin-api服务，可以看到QPS设置为10时访问没问题。

<img width="1506" alt="image-20240823111259823" src="https://github.com/user-attachments/assets/391cb8eb-f8e9-4531-9897-05287b9b9441">
修改Nacos配置进行限流（修改count为2）

<img width="1189" alt="image-20240823111430213" src="https://github.com/user-attachments/assets/92b02445-524e-4a45-90af-7c33f294021e">
查看sentinel的record日志可以看到已经修改成功。

<img width="1347" alt="image-20240823111604519" src="https://github.com/user-attachments/assets/566133f4-74bf-425b-88d4-0c76b4358e37">

测试后可以发现已经生效，1s内如果发送三个请求会被拦截一个。

<img width="1225" alt="image-20240823111854845" src="https://github.com/user-attachments/assets/c8f5bf58-030d-45fa-a0c7-b6b9e5640846">
但是Sentinel Dashboard并未显示对应的值。

<img width="1489" alt="image-20240823112005888" src="https://github.com/user-attachments/assets/d6bc989b-0bac-450d-9b6e-4e71d0dba421">
### 情况一

在上面的情况中我们直接添加流控规则，将QPS的阈值设置为10。

<img width="1510" alt="image-20240823112259985" src="https://github.com/user-attachments/assets/e1ef236d-cd6d-478d-b786-6629e451b7bd">
可以看到并未生效

<img width="1224" alt="image-20240823112409493" src="https://github.com/user-attachments/assets/8b2e15b8-0da0-4f57-8f27-d6b6066081dd">
但是Dashboard控制台显示修改成功。

<img width="1329" alt="image-20240823112548749" src="https://github.com/user-attachments/assets/ebc11721-c066-48dc-b148-d829df169af8">

### 情况二

重启网关和其他服务，先从dashboard配置再从nacos配置

此时nacos中的配置如下

```json
[
	{
        "resource": "system-admin-api",
        "resourceMode": 0,
        "count": 2,
        "grade": 1,
		"controlBehavior": 0,
        "intervalSec": 10,
        "burst": 0,
        "maxQueueingTimeoutMs": 1000
	}
]
```

dashboard的流控规则界面如下，由于是从内存中读取，每次的流控规则需要重新配置。

<img width="1270" alt="image-20240823112842025" src="https://github.com/user-attachments/assets/a4ed33f1-e494-4df8-ae8e-7e9c36d72cd8">
但是从实时监控的面板上可以看到nacos中的配置已经生效了

<img width="1222" alt="image-20240823112958524" src="https://github.com/user-attachments/assets/0392970d-f132-454a-81b3-62a18d757043">
此时通过dashboard配置流控规则将QPS设置为1。

<img width="1249" alt="image-20240823113314096" src="https://github.com/user-attachments/assets/4678d222-dfa7-42ea-bf4b-590264b5170e">
可以看到已经生效

<img width="1266" alt="image-20240823113406477" src="https://github.com/user-attachments/assets/63c9f5d6-c007-4bf7-97f8-007755237412">
然后再去nacos发布如下配置

<img width="1191" alt="image-20240823113444349" src="https://github.com/user-attachments/assets/bd3e8d0e-f13c-4e25-84ec-37fc0fd9c513">
在sentinel record日志中可以看到已经更新了

<img width="1349" alt="image-20240823113542232" src="https://github.com/user-attachments/assets/06b9e282-94fe-4244-af83-dcca53d1b6c4">
但是实际测试中显示更新失败

<img width="1234" alt="image-20240823113653367" src="https://github.com/user-attachments/assets/02c7ab9e-c284-4aeb-afa9-001612065dd4">
同时dashboard中显示的流控规则的QPS没有改变。

<img width="1238" alt="image-20240823113717103" src="https://github.com/user-attachments/assets/f2c48ddd-dd74-44a0-8324-39154c8b5381">
### Describe what you expected to happen

Nacos发布流控规则能够同步到Sentinel Dashboard

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3. 

### Tell us your environment

版本说明：nacos=2.4.0、Sentinel Dashborad=1.8.8、spring.cloud.alibaba.version=2023.0.1.2
