### ISSUE TITLE
sentinel+dashboard+nacos 无法自动注册资源以及流控规则不生效（Unable to automatically register resources and Flow rules are not effective）

### ISSUE THREAD

**Issue by selway** [alibaba/Sentinel#3482]
我目前不确实是我的使用问题还是真的存在BUG，所以提交一条空白的问题。
I am currently not sure if it is a usage issue or if there is a genuine bug, so I am submitting a blank question.

## Issue Description

Type: *bug* or *question*

### Describe what happened (or what feature you want)

我通单元测试的示例对Sentinel Dashboard的流控规则进行了Nacos持久配置；目前发生了两个问题：
I have performed Nacos persistent configuration for the flow control rules of Sentinel Dashboard through the examples of unit tests. Currently, two problems have occurred:

1. 微服务内的API不会自动注册到Dashboard；
2. 通过注解SentinelResource标记API后，可以注册到Dashboard了，但是配置限流规则后不生效；

EN
1. The APIs within the microservice will not be automatically registered to the Dashboard.
2. After marking the APIs with the annotation SentinelResource, they can be registered to the Dashboard. However, the configured flow rules do not take effect.

![image](https://github.com/user-attachments/assets/931ad075-26b0-4aac-a215-d7af9c015dc1)
![image](https://github.com/user-attachments/assets/52a62ea2-0f0c-4d59-beb7-82d6c63f8484)
![image](https://github.com/user-attachments/assets/04020b9c-29ba-4dbd-8fdc-6828c3cc0720)

### Describe what you expected to happen

1. 有什么方式可以在不使用SentinelResource情况下将API自动注册到Dashboard；
2. 让流控规则生效；

EN
1. What methods are there to automatically register APIs to the Dashboard without using SentinelResource?
2. Make the flow control rules take effect.

### How to reproduce it (as minimally and precisely as possible)

1. 使用的附件的pom、yml、Test1Controller，创建一个简单的spring-boot3 项目
2. 启动项目，启动dashboard
3. 配置流程控规则
4. 压测

EN
1. Use the pom.xml, application.yml and Test1Controller in the attachment to create a simple Spring Boot 3 project.
2. Start the project and start the Sentinel Dashboard.
3. Configure the flow control rules.
4. Conduct a load test.

### Tell us your environment

JDK：17
spring-boot：3.2.4
spring-cloud.version：2023.0.1
spring-cloud-alibaba.version：2023.1.0
sentinel.version：1.8.8
sentinel-dashboard.version：1.8.8
nacos: 2.4.3

### Anything else we need to know?

demo pom
``` xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.2.4</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>
    <groupId>com.demo</groupId>
    <artifactId>sentinel-demo-spring-cloud-alibaba</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <name>sentinel-demo-spring-cloud-alibaba</name>
    <description>sentinel-demo-spring-cloud-alibaba</description>
    <url/>
    <licenses>
        <license/>
    </licenses>
    <developers>
        <developer/>
    </developers>
    <scm>
        <connection/>
        <developerConnection/>
        <tag/>
        <url/>
    </scm>
    <properties>
        <java.version>17</java.version>
        <spring-cloud.version>2023.0.1</spring-cloud.version>
        <spring-cloud-alibaba.version>2023.0.1.0</spring-cloud-alibaba.version>
        <sentinel.version>1.8.8</sentinel.version>
    </properties>
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>${spring-cloud.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>com.alibaba.cloud</groupId>
                <artifactId>spring-cloud-alibaba-dependencies</artifactId>
                <version>${spring-cloud-alibaba.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>

        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-sentinel</artifactId>
        </dependency>

        <dependency>
            <groupId>com.alibaba.csp</groupId>
            <artifactId>sentinel-datasource-nacos</artifactId>
        </dependency>

        <dependency>
            <groupId>com.alibaba.csp</groupId>
            <artifactId>sentinel-transport-simple-http</artifactId>
        </dependency>

        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
            <exclusions>
                <exclusion>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-starter-logging</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <excludes>
                        <exclude>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                        </exclude>
                    </excludes>
                </configuration>
            </plugin>
        </plugins>
    </build>
    <repositories>
        <repository>
            <id>spring-milestones</id>
            <name>Spring Milestones</name>
            <url>https://repo.spring.io/milestone</url>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </repository>
    </repositories>

</project>
```

demo config
```  yaml
server:
  port: 8801
spring:
  application:
    name: sentinel-demo
  cloud:
    # 集成 Sentinel 进行限流、熔断降级
    sentinel:
      web-context-unify: false
      eager: true
      enabled: true
      transport:
        # 指定 Sentinel 控制台的地址和端口
        dashboard: localhost:8080
        # 可选 指定 Sentinel 服务端口，默认为8719
        # port: 8719
        clientIp: 172.16.30.208
      filter:
        enabled: false
      datasource:
        flow:
          nacos:
            server-addr: localhost:8848
            group-id: SENTINEL_GROUP
            username: nacos
            password: nacos
            data-id: ${spring.application.name}-flow-rules
            data-type: json
            rule-type: flow
        degrade:
          nacos:
            server-addr: localhost:8848
            group-id: SENTINEL_GROUP
            username: nacos
            password: nacos
            data-id: ${spring.application.name}-degrade-rules
            rule-type: degrade
        system:
          nacos:
            server-addr: localhost:8848
            groupId: SENTINEL_GROUP
            username: nacos
            password: nacos
            dataId: ${spring.application.name}-system-rules
            data-type: json
            rule-type: system
        authority:
          nacos:
            server-addr: localhost:8848
            groupId: SENTINEL_GROUP
            username: nacos
            password: nacos
            dataId: ${spring.application.name}-authority-rules
            data-type: json
            rule-type: authority
        param-flow:
          nacos:
            server-addr: localhost:8848
            groupId: SENTINEL_GROUP
            username: nacos
            password: nacos
            dataId: ${spring.application.name}-param-flow-rules
            data-type: json
            rule-type: param-flow
      log:
        dir: ${user.home}/logs/csp/demo/

```

demo Test1Controller
``` java
package com.demo.sentineldemo.controller;


import com.alibaba.csp.sentinel.annotation.SentinelResource;
import org.springframework.web.bind.annotation.*;

//@SentinelResource("/api/test1")
@RestController
@RequestMapping("/api/test1")
public class Test1Controller {

    @SentinelResource("/api/test1/get")
    @GetMapping("/get")
    public String get() {
        return "get";
    }

    @PostMapping("/post")
    public String post() {
        return "post";
    }

    @GetMapping("/get/{id}")
    public String get(@PathVariable String id) {
        return "get-id";
    }
}
```
